app:
  llmType: "LOCAL"
  llmConfig:
    # local:
    #   httpModelUrl: "http://localhost:8000/v1"
    openai:
      apiKey: "test"
      customUrl: "http://localhost:8000/v1"
      modelName: "GPT_4O_MINI"

database:
  host: "localhost" # -> Defines the host to be used in the database connection (URL or IP) 
  port: 3306 # -> Defines the port to be used
  user: "root" # -> Defines the user to be used
  password: "" # -> Defines the password to be used
  databaseName: "tcc_test" # -> Defines the database name to be used
  databaseType: "MYSQL" # MYSQL, POSTGRESQL -> Defines the database type to be used