app:
  llm_type: "LOCAL"
  llmConfig:
    local:
      httpModelUrl: "https://localhost:8080/local/llm/api"
      conversationApiPath: "/conversation"

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: ""
  databaseName: "db_test"
  databaseType: "MYSQL"